# Auditing the "Revenue Cycle" AI

In [5]:
import pandas as pd
import sqlite3

# Create a simulated dataset of Billing Codes and AI Suggestions
billing_data = {
    "bill_id": [901, 902, 903, 904, 905, 906, 907],
    "department": ["Acupuncture", "Cardiology", "Acupuncture", "Neurology", "Acupuncture", "Cardiology", "Neurology"],
    "procedure_name": ["Acupuncture Session", "EKG", "Acupuncture Session", "MRI Scan", "Acupuncture Session", "EKG", "Consultation"],
    "standard_cost": [80, 150, 80, 1200, 80, 150, 200],
    "ai_suggested_billing": [80, 150, 500, 1200, 80, 150, 200]
}
# save data into DataFrame
df_billing_data = pd.DataFrame(billing_data)
# connect the sqlite
connt = sqlite3.connect(":memory:")
# save dataSet into memory
df_billing_data.to_sql("billing_audit", connt, index=False, if_exists = "replace")
# function to run the query
def run_query(query):
    return pd.read_sql_query(query, connt)
print("********************************** Financial Compliance Database!!! *************************")

********************************** Financial Compliance Database!!! *************************

# Detecting Over-Billing (The "Fraud" Check)

In [9]:
# query for all dataset for a quick view
all_data = "SELECT * FROM billing_audit" 
print("*************************** data_table to view **********************")
display(run_query(all_data))
print("/////////////////////////////////////////////////////////////////////////////\n")
# query to find any rows where the ai_suggested_billing is greater than the standard_cost
over_billing = """
SELECT bill_id, department, procedure_name, standard_cost, ai_suggested_billing FROM billing_audit
WHERE ai_suggested_billing > standard_cost
"""
print("******************************* detecting over_billing **********************")
display(run_query(over_billing))

*************************** data_table to view **********************

,bill_id,department,procedure_name,standard_cost,ai_suggested_billing
0,901,Acupuncture,Acupuncture Session,80,80
1,902,Cardiology,EKG,150,150
2,903,Acupuncture,Acupuncture Session,80,500
3,904,Neurology,MRI Scan,1200,1200
4,905,Acupuncture,Acupuncture Session,80,80
5,906,Cardiology,EKG,150,150
6,907,Neurology,Consultation,200,200

/////////////////////////////////////////////////////////////////////////////

******************************* detecting over_billing **********************

,bill_id,department,procedure_name,standard_cost,ai_suggested_billing
0,903,Acupuncture,Acupuncture Session,80,500

# Total "Value at Risk"

In [10]:
# query that calculates the total difference (sum) between the ai_suggested_billing and the standard_cost for the entire dataset.
total_billing = """
SELECT SUM(ai_suggested_billing - standard_cost) AS total_discrepancy
FROM billing_audit
"""
print("/////////////////////////////////////////////////////////////////////////////\n")
print("************************************ total_discrepancy ************************* ")
display(run_query(total_billing))

/////////////////////////////////////////////////////////////////////////////

************************************ total_discrepancy *************************

   total_discrepancy
0                420