# Creating mock data

In [7]:
import pandas as pd
import sqlite3
# create a simulated access log dataset
access_log_data = {
    "log_id": [5001, 5002, 5003, 5004, 5005, 5006, 5007, 5008],
    "user_id": ["Dr_Smith", "Nurse_Joy", "Dr_Smith", "Admin_Kelly", "Nurse_Joy", "Dr_Smith", "Admin_Kelly", "Dr_Strange"],
    "patient_id": ["P01", "P02", "P03", "P01", "P05", "P08", "P09", "P01"],
    "access_time": ["09:15", "11:30", "14:45", "02:10", "10:00", "23:50", "03:45", "13:00"],
    "department": ["Cardiology", "ER", "Cardiology", "Billing", "ER", "Cardiology", "Billing", "Neurology"]   
}
# put data in the dataFrame
df_logs = pd.DataFrame(access_log_data)
# connect to sql
connt = sqlite3.connect(":memory:")
# save the dataSet
df_logs.to_sql("access_logs", connt, index = False, if_exists = "replace")
# simple print fuction 
print("Security Audit Database is ready!!!")

Security Audit Database is ready!!!

# Midnight Access Check

In [9]:
# create function to read the dataFrame 
def run_log(query):
    return pd.read_sql_query(query, connt)
# Query -- find the midnight access of the patient data
query_midnight_access = """
SELECT * FROM access_logs WHERE access_time >= '00:00' AND access_time <= '05:00'
"""
print("....Midnight access times have been detected.....")
display(run_log(query_midnight_access))

....Midnight access times have been detected.....

   log_id      user_id patient_id access_time department
0    5004  Admin_Kelly        P01       02:10    Billing
1    5007  Admin_Kelly        P09       03:45    Billing

# Detecting Data Scraping

In [14]:
# query --- how many unique patients data have been accessed by a user
query_numberof_patients = """
SELECT user_id, COUNT(DISTINCT patient_id) FROM access_logs GROUP BY user_id
"""
print("..... Data Scraping has been found!!! ...")
display(run_log(query_numberof_patients))

..... Data Scraping has been found!!! ...

       user_id  COUNT(DISTINCT patient_id)
0  Admin_Kelly                           2
1     Dr_Smith                           3
2   Dr_Strange                           1
3    Nurse_Joy                           2